name: ZH_ZToLL_HToInvisible_M125_UL17_full
is_sim: true
cross_section: 0.07924
num_events: 989994
num_selected_events: 989994
mean_weight: 0.079326675874601252
zz_2l2nu: false
files:
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/0162C356-7991-5149-8EE4-B34F8468D970.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/02C0A938-7E43-E94B-843B-17DA14BEE689.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/0530D1A9-C404-0841-B517-5BEE99763C2B.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/18BA5D69-233B-094A-9DDB-63F2FEAC604C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/1EBF11DD-90A3-6644-A2C8-C7FED525C8C1.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/20E8DFC5-BCFA-8549-A3B7-6D78DAF91122.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/2611B6FD-3248-AC43-8A27-3952CACF8FA4.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/43125CC2-6E4B-E44A-84F5-34323BECF25C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/437472E0-AA72-7645-86C6-B6AA8154FE68.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/475207E1-1506-FB44-A3E7-1F73CE09C7B5.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/491BDB22-3624-FF43-AEE9-EA7104C6D35C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/4E46C301-E8FF-AA49-A6AF-AE77F7B63431.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/50E104FF-8EFF-0D47-9525-5672338056CC.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/61C1AB10-0A06-3C4C-9236-2689D2A66BFA.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/660DBE03-52E8-5D43-A5AD-B09A2C978618.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/6EC592F8-D5A9-3447-B3FB-4F391C7DD6CE.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/72A68C4C-0A89-BA43-B191-D5B0E9081847.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/7F9B1E4F-399A-A342-B25D-65CD327361D5.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/8E8889FF-8906-8A43-9C8A-EB25BDCF5029.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/928CA4B5-6F20-E54D-93B5-3A2A68396DCA.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/93C1DBF3-B20F-FB4E-B6CC-71575A871612.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/98CD1B9A-7EC8-5A4B-B555-B0B99600249B.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/A6E74BC8-D8FB-9A4A-B28F-FB6B4C99FA80.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/B01E6033-6FBF-E848-8C88-31EAD79A9807.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/BE0F332B-8B83-CF46-B941-D48B0B321B30.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/C2E64389-EC09-A64F-AF47-E28D3E7DB975.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/CC0B6212-32D8-3946-9DE8-8AAF9CCCDDE5.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/CFEFC169-3608-2E42-A093-9B46C29DAE93.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/D17ED0F0-E93F-DF45-B551-B164690B2A92.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/DDFBE692-170C-2E47-A893-DBF61CA95818.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/E792D6E4-2A86-7D40-9836-2EB33A4E2212.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/E9DC5FD6-76D8-A14B-B803-6BB46B2FC925.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2017/F721C8CD-D7ED-E846-9E82-16F7ABEDB27A.root
