name: ZH_ZToLL_HToInvisible_M125_UL18_full
is_sim: true
cross_section: 0.07924
num_events: 993986
num_selected_events: 993986
mean_weight: 0.079317736566309791
zz_2l2nu: false
files:
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/09335DBE-3205-7447-9B24-47AEEF206352.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/0BD98289-837C-2844-87EA-539AA3C83487.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/0DFB622E-779A-8D49-98A1-ADABCEA0D691.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/104EECC9-8369-AB4C-91E5-2BD6F36D82A2.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/21DFD818-22E1-814D-B2DF-41B192A5A918.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/2AB686EC-5C75-CB4E-9D0A-15E3DFC21FD6.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/2B11136D-002D-9447-9BEC-C611E9D290BD.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/4506F88A-E3BC-104B-A593-61C8B2BE6476.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/4AC4F658-48BE-5B40-A33A-2DC64E4233A5.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/58002DEC-17B3-6945-9E13-0596E0887018.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/5966CD52-EA68-E745-9827-3CA69C02D7E0.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/5D0ED74D-AF04-064F-8D44-25D685A46584.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/67CC5E8F-5BEC-4A42-91DA-EB3EB8CC0AB5.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/6806B36C-3BA4-1540-884E-9AA1C7A352BA.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/73ACCF8E-660B-6248-B082-7E9DFF82AD22.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/9728E5E1-F8C0-1D44-A729-8316EA27C75C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/A5E7E753-390C-5B44-9990-AAD5664C157B.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/A730F573-70DE-D143-AB6F-7DAADE71419C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/A9AE4842-D772-0C4A-9997-73FC0944B0A3.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/BEA8A1B4-E4FC-D349-8B00-9AC424D03A3C.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/D2DD0073-B80F-E447-B0C9-0F1FD9B7C9ED.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/DE830A42-E79C-524B-A085-EABA49DCE3CF.root
- /eos/user/l/liwe/monoz_full_dnn/inputs/signal_nanoaod/2018/F0F1F6FC-AF74-DC4E-A6D3-FB4FE7D57D9D.root
