files:
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p0_Dilepton-MuonEG_1.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p0_Dilepton-MuonEG_2.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_1.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_2.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_3.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_4.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_5.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_6.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_7.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_8.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p1_Dilepton-MuonEG_9.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_12.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_17.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_14.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_16.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_18.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_15.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_11.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_19.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_13.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_10.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_1.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_2.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_3.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_4.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_5.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_6.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_7.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_8.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2016/MuonEG/MuonEG_p2_Dilepton-MuonEG_9.root
num_selected_events: 172
stem: MuonEG
