input_dir: "../../batch_singleelectron_2017/merged"
output_dir: "../../batch_singleelectron_2017/merged"
samples:
  - name: 'Data'
    multiplier: '1.0'
  - name: 'QCD'
    multiplier: '-1.0'
  - name: 'DYJetsToLL_PtZ'
    multiplier: '-1.0'
  - name: 'GJets'
    multiplier: '-1.0'
  - name: 'TTJets'
    multiplier: '-1.0'
  - name: 'ST_s-channel'
    multiplier: '-1.0'
  - name: 'ST_t-channel'
    multiplier: '-1.0'
  - name: 'ST_tW'
    multiplier: '-1.0'
  - name: 'WWTo1L1Nu2Q'
    multiplier: '-1.0'
  - name: 'WWTo2L2Nu'
    multiplier: '-1.0'
  - name: 'WZTo1L1Nu2Q'
    multiplier: '-1.0'
  - name: 'WZTo1L3Nu'
    multiplier: '-1.0'
  - name: 'WZTo2Q2L'
    multiplier: '-1.0'
  - name: 'WZTo3LNu'
    multiplier: '-1.0'
  - name: 'ZZTo2L2Nu'
    multiplier: '-1.0'
  - name: 'ZZTo2Q2L'
    multiplier: '-1.0'
  - name: 'ZZTo4L'
    multiplier: '-1.0'

fake_ratio_filepath: "../ratiosWJets/fakeRatio/ratios_2017.root"
photon_trigger_efficiency_filepath: "../ratiosWJets/singlePhoton_cutbaseID_data/2017.root"
electron_trigger_efficiency_filepath: "../ratiosWJets/singleElectron_data/fit_UL2017_Efficiency.root"
