# This is the configuration file to get plots from the ZGammaTrees analysis.

selections:
- formula: "ptmiss >= 0."
  weight: weight
  tag: baseline
  label: "baseline selection"

- formula: "lepton_cat == 0"
  weight: weight
  tag: ee
  label: "$ee$"

- formula: "lepton_cat == 1"
  weight: weight
  tag: mumu
  label: "$\\mu\\mu$"

- formula:  "photon_pt >= 55."
  weight: weight
  tag: photon_pt_geq55
  label: "photon_pt >= 55."

- formula: "lepton_cat == 0 && photon_pt >= 55."
  weight: weight
  tag: ee__photon_pt_geq55
  label: "$ee$ (photon_pt >= 55.)"

- formula: "lepton_cat == 1 && photon_pt >= 55."
  weight: weight
  tag: mumu__photon_pt_geq55
  label: "$\\mu\\mu$ (photon_pt >= 55.)"

- formula:  "abs(photon_eta) <= 1.4442 && photon_pt >= 55."
  weight: weight
  tag: barrel_photon_pt_geq55
  label: "barrel, photon_pt >= 55."

- formula:  "abs(photon_eta) >= 1.5660 && photon_pt >= 55."
  weight: weight
  tag: endcap_photon_pt_geq55
  label: "endcap, photon_pt >= 55."

samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
  # - label: "$Z\\gamma \\to 2\\nu\\gamma$"
    # files: [ZGTo2NuG, ZGTo2NuG_PtG-130]
    # color: gold
  - label: "$Z\\gamma \\to 2\\ell\\gamma$"
    files: [ZGTo2LG]
    # files: [ZLLGJets]
    color: maroon
  # - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
  #   files: [WGToLNuG]
  #   color: blueviolet
  # - label: "$\\gamma + $ jets"
  #   files: [GJets]
  #   color: darkorange
  # - label: "$W + $ jets $ \\to \\ell\\nu$"
  #   files: [WJets]
  #   color: palevioletred
  # - label: "QCD (HT > 100)"
  #   files: [QCD]
  #   color: darkgray
  # - label: "Drell-Yan"
    # files: [DYJetsToLL]
    # files: [DYJetsToLL-amcatnlo]
  - label: "Drell-Yan\n(PtZ-binned)"
    files: [DYJetsToLL_PtZ]
    color: steelblue
  - label: "$t\\bar t\\gamma + $ jets"
    files: [TTGJets]
    color: greenyellow

variables:
- formula: "photon_pt"
  binning:
    default:
      range: [20., 1400.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma
- formula: "photon_pt"
  binning:
    default:
      range: [20., 720.]
      bins: 20
  x_scale: linear
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma_linear
- formula: "photon_r9"
  binning:
    default:
      range: [0.4, 1.2]
      bins: 40
  x_scale: linear
  label: "$\\gamma_{R9}$"
  unit: 
  tag: r9_gamma
- formula: "jet_size"
  binning:
    default:
      range: [0, 6]
      bins: 6
  x_scale: linear
  label: "$N_{jets}$"
  unit: 
  tag: njets
- formula: "ptmiss"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
- formula: "photon_eta"
  binning:
    default:
      range: [-2., 2.]
      bins: 40
  x_scale: linear
  label: "$\\eta^{\\gamma}$"
  unit: 
  tag: eta_gamma
- formula: "photon_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\phi^{\\gamma}$"
  unit: 
  tag: phi_gamma
- formula: "mT"
  binning:
    default:
      range: [200., 2000.]
      bins: 20
  x_scale: log
  label: "$m_\\mathrm{T}$"
  unit: GeV
  tag: mt
- formula: "num_pv_good"
  binning:
    default:
      range: [0., 75.]
      bins: 20
  x_scale: linear
  label: "Number of good vertices"
  unit:
  tag: numpvgood
- formula: "lepton_pt[0]"
  binning:
    default:
      range: [5., 250.]
      bins: 20
  x_scale: log
  label: "$p_{\\mathrm{T}}(\\ell_1)$"
  tag: l1_pt
- formula: "lepton_pt[1]"
  binning:
    default:
      range: [5., 250.]
      bins: 20
  x_scale: log
  label: "$p_{\\mathrm{T}}(\\ell_2)$"
  tag: l2_pt
- formula: "lepton_eta[0]"
  binning:
    default:
      range: [-2.5, 2.5]
      bins: 40
  x_scale: linear
  label: "$\\eta(\\ell_1)$"
  tag: l1_eta
- formula: "lepton_eta[1]"
  binning:
    default:
      range: [-2.5, 2.5]
      bins: 40
  x_scale: linear
  label: "$\\eta(\\ell_2)$"
  tag: l2_eta
- formula: "ll_pt"
  binning:
    default:
      range: [5., 500.]
      bins: 20
  x_scale: log
  label: "$p_{\\mathrm{T}}(\\ell\\ell)$"
  tag: ll_pt
