# This is an example configuration file for script plot_data_sim.py

# Variants of events selection to apply. Each element of this list is a mapping
# with the following keys:
#   formula:  Formula defining which events are to be kept.
#   weight:   Formula to compute event weight in simulation.
#   weight_data:  Formula to compute event weight in data. Optional; by default
#                 events in data are not weighted.
#   tag:      String uniquely identifying this selection.
#   label:    LaTeX label to describe this selection in plots. Optional;
#             defaults to the value of tag.
#   blind:    Requests that data are kept blind. The plots will put data points
#             at total expectation instead. Optional; defaults to false.
selections:
- formula: " (lepton_cat == 0 || lepton_cat == 1 )"
  weight: weight
  tag: baseline
  label: "$ll, inclusive$"

- formula: "(lepton_cat == 0 || lepton_cat == 1 ) &&jet_cat == 0"
  weight: weight
  tag: eq0jet
  label: "$ll, 0j$"

- formula: "(lepton_cat == 0 || lepton_cat == 1 ) && jet_cat == 1"
  weight: weight
  tag: geq1jet
  label: "$ll, = 1j$"

- formula: "(lepton_cat == 0 || lepton_cat == 1 ) && jet_cat == 2"
  weight: weight
  tag: geq2jet
  label: "$ll$, $\\geq$ 2j"

- formula: "( lepton_cat == 1 ) &&jet_cat == 0"
  weight: weight
  tag: mumu_eq0jet
  label: "$\\mu\\mu, 0j$"

- formula: "( lepton_cat == 1 ) && jet_cat == 1"
  weight: weight
  tag: mumu_geq1jet
  label: "$\\mu\\mu, = 1j$"

- formula: "( lepton_cat == 1 ) && jet_cat == 2"
  weight: weight
  tag: mumu_geq2jet
  label: "$\\mu\\mu$, $\\geq$ 2j"

- formula: "( lepton_cat == 0 ) &&jet_cat == 0"
  weight: weight
  tag: ee_eq0jet
  label: "$ee, 0j$"

- formula: "( lepton_cat == 0 ) && jet_cat == 1"
  weight: weight
  tag: ee_geq1jet
  label: "$ee, = 1j$"

- formula: "( lepton_cat == 0 ) && jet_cat == 2"
  weight: weight
  tag: ee_geq2jet
  label: "$ee$, $\\geq$ 2j"

- formula: "( lepton_cat == 2 )"
  weight: weight
  tag: emu
  label: "$e\\mu, inclusive$"

# Information about input files and decoration for different processes
samples:
  # Optional prefix that will be added to all file paths. Can also be provided
  # as a command line option for the script (which takes precedence if both are
  # given).
  path_prefix: ""

  # Optional name of tree to read from input files. Defaults to "Vars".
  tree_name: Vars

  # Optional label for the type of entries in the source tree. Used as a part of
  # the label of the y axis. Defaults to "Events".
  entries_label: Events

  # Data sample. Each file name is prepended with the path prefix above, and
  # several standard endings are tried.
  data:
    files: [Data]
    tag: "Data"

  # Samples for simulation. Each element of the list is a mapping with the
  # following keys:
  #   label:  LaTeX label for this process to be used in plots.
  #   files:  Name for input files. Processed in the same way as for data.
  #   color:  Color for this process.
  simulation:
  #- label: "$gg \\to (H) \\to ZZ$"
  #  files: [GGToZZ_BSI]
  #  color: crimson
  # - label: "VBF"
  #   files: [VBFToZZ_BSI_Phantom]
  #   color: darkviolet
  # - label: "VBS $ZZ \\to 2\\ell 2\\nu$ \n(NLO)"
  #   files: [VBS_ZZTo2E2Nu, VBS_ZZTo2Mu2Nu]
  #   color: darkviolet
  - label: "VVV" 
    tag: "VVV" 
    files: [WWW, WWZ, WZZ, ZZZ]
    color: mediumpurple
  - label: "$gg \\to ZZ \\to 2\\ell 2\\nu$"
    tag: "ggZZ"
    files: [GGToZZ]
    color: crimson
  # - label: "$gg \\to WW \\to 2\\ell 2\\nu$"
  #   files: [GGToWW]
  #   color: pink
  - label: "$q\\bar q \\to ZZ$"
    tag: "qqZZ"
    files: [ZZTo2L2Nu,ZZTo2Q2L, ZZTo4L]
    color: darkorange
  - label: "$WW$, $WZ$"
    tag: "WW+WZ"
    files: [WWTo2L2Nu, WZTo2Q2L, WZTo3LNu]
    color: lightseagreen
  - label: "$t\\bar t$"
    tag: "ttbar"
    files: [TTTo2L2Nu]
    color: greenyellow
  - label: "Single $t$, $tW$"
    tag: "ST"
    files: [ST_s-channel, ST_t-channel, ST_tW]
    color: mediumblue
  - label: "Drell-Yan"
    tag: "DY"
    files: [DYJetsToLL_PtZ]
    color: steelblue
  - label: "Other"
    tag: "Other"
    files: [TTWJetsToLNu, TTZToLLNuNu_M-10, tZq_ll]
    color: slateblue


# Variables whose distributions are to be plotted. Each element of the list is a
# mapping with the following keys:
#   formula:  Formula to compute the variable.
#   tag:      String uniquely identifying the variable.
#   label:    LaTeX label for this variable to be used in plots. Optional;
#             defaults to the value of tag.
#   binning:  Binning for each selection, with the selection's tag used as the
#             key of the mapping. It is also possible to provide a default
#             bining using key "default" instead of the selection's tag.
#   x_scale:  Indicates whether linear or log scale should be used for x axis
#             for this variable. Allowed values are "linear" and "log".
#             Optional; defaults to "linear".
#   y_scale:  Scale for y axis for this variable. Optional; defaults to "log".
#             Otherwise similar to x_scale.
#   unit:     Unit for measurement for this variable. Optional.
# The binning is described with the following keys:
#   bins:     Number of bins or a sequence that defines binning.
#   range:    Full range. Can only be given when value of bins is a number.
#   scale:    Selection-specific scale for x axis. It has the same meaning as
#             the variable-level scale described above. Optional; defaults to
#             the variable-level scale. If both are given, the
#             selection-specific scale takes precedence.
variables:
- formula: "ll_pt"
  binning:
    default:
      range: [60., 450.]
      bins: 15
  x_scale: log
  label: "$p_\\mathrm{T}^{\\ell\\ell}$"
  unit: GeV
  tag: pt_ll

- formula: "ptmiss"
  binning:
    default:
      range: [12., 1200.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^\\mathrm{miss}$"
  unit: GeV
  tag: pt_miss

- formula: "ll_mass"
  binning:
    default:
      range: [70., 110.]
      bins: 20
  x_scale: log
  label: "$m_{\\ell\\ell}$"
  unit: GeV
  tag: z_mass

- formula: "jet_cat"
  binning:
    default:
      range: [0, 3]
      bins: 3
  x_scale: linear
  label: "jet_cat"
  unit: 
  tag: jet_cat

#- formula: "jet_size"
#  binning:
#    default:
#      range: [0, 6]
#      bins: 6
#  x_scale: linear
#  label: "njets"
#  unit: 
#  tag: njets

#- formula: "lepton_pt[0]"
#  binning:
#    default:
#      range: [20., 250.]
#      bins: 20
#  x_scale: log
#  label: "$p_{\\mathrm{T}}(\\ell_1)$"
#  tag: l1_pt

#- formula: "lepton_pt[1]"
#  binning:
#    default:
#      range: [20., 250.]
#      bins: 20
#  x_scale: log
#  label: "$p_{\\mathrm{T}}(\\ell_2)$"
#  tag: l2_pt

- formula: "dphi_visibles_ptmiss"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\Delta\\phi(\\ell\\ell + \\mathrm{jets}, p_\\mathrm{T}^{miss})$"
  unit: 
  tag: dphi_visibles_ptmiss
