# This is the configuration file to get plots from the PhotonTrees analysis.

selections:
- formula: "ptmiss >= 0."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: baseline
  label: "baseline selection"

- formula: "ptmiss < 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_l120
  label: "$p_\\mathrm{T}^\\mathrm{miss} < 120.$"

- formula: "ptmiss >= 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_geq120
  label: "$p_\\mathrm{T}^\\mathrm{miss} \\geq 120.$"

- formula: "jet_size == 0"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: eq0jet
  label: "0j"

- formula: "jet_size == 1"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: eq1jet
  label: "1j"

- formula: "jet_size >= 2"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: geq2jet
  label: "$\\geq$ 2j"

- formula: "jet_size >= 2 && abs(photon_eta) <= 1.4442"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: barrel_geq2jet
  label: "barrel, $\\geq$ 2j"

- formula: "jet_size >= 2 && abs(photon_eta) >= 1.5660"
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: endcap_geq2jet
  label: "endcap, $\\geq$ 2j"

- formula: "jet_size == 0 && ptmiss < 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_l120_eq0jet
  label: "$p_\\mathrm{T}^\\mathrm{miss} < 120.$, 0j"

- formula: "jet_size == 0 && ptmiss >= 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_geq120_eq0jet
  label: "$p_\\mathrm{T}^\\mathrm{miss} \\geq 120.$, 0j"

- formula: "jet_size >= 2 && ptmiss < 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_l120_geq2jet
  label: "$p_\\mathrm{T}^\\mathrm{miss} < 120.$, $\\geq$ 2j"

- formula: "jet_size >= 2 && ptmiss >= 120."
  weight: weight
  weight_data: trigger_weight * beam_halo_weight
  tag: ptmiss_geq120_geq2jet
  label: "$p_\\mathrm{T}^\\mathrm{miss} \\geq 120.$, $\\geq$ 2j"

samples:
  path_prefix: ""
  data:
    files: [Data]
  simulation:
    - label: "$Z\\gamma \\to 2\\nu\\gamma$"
      files: [ZNuNuGJets]
      color: gold
    # - label: "$Z(\\to 2\\nu) + $jets\n(HT > 100)"
    #   files: [ZJetsToNuNu]
    #   color: steelblue
    - label: "$W\\gamma \\to \\ell\\nu\\gamma$"
      files: [WGToLNuG]
      color: blueviolet
    - label: "$t\\gamma$, $tt\\gamma$"
      files: [TTGJets, TGJets]
      color: limegreen
    - label: "$\\gamma + $jets"
      files: [GJets]
      color: darkorange
    # - label: "WJetsToLNu\n(LO)"
    #   files: [WJets]
    - label: "WJetsToLNu\n(NLO)"
      files: [WJetsToLNu_0J, WJetsToLNu_1J, WJetsToLNu_2J]
    # - label: "WJetsToLNu\n(Data-driven)"
    #   files: [WJets_Data-driven_Data, WJets_Data-driven_GJets, WJets_Data-driven_QCD, WJets_Data-driven_DYJetsToLL_PtZ,  WJets_Data-driven_ST_s-channel,  WJets_Data-driven_ST_t-channel,  WJets_Data-driven_ST_tW]
      color: palevioletred
    - label: "QCD (HT > 100)"
      files: [QCD]
      color: darkgray

variables:
- formula: "photon_pt"
  binning:
    default:
      range: [60., 1400.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma
- formula: "photon_pt"
  binning:
    default:
      range: [60., 720.]
      bins: 20
  x_scale: linear
  label: "$p_\\mathrm{T}^{\\gamma}$"
  unit: GeV
  tag: pt_gamma_linear
- formula: "jet_size"
  binning:
    default:
      range: [0, 6]
      bins: 6
  x_scale: linear
  label: "$N_{jets}$"
  unit: 
  tag: njets
- formula: "ptmiss"
  binning:
    default:
      range: [10., 1000.]
      bins: 20
  x_scale: log
  label: "$p_\\mathrm{T}^{miss}$"
  unit: GeV
  tag: pt_miss
- formula: "ptmiss_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$p_\\mathrm{T}^{miss}$"
  unit: 
  tag: phi_miss
- formula: "photon_eta"
  binning:
    default:
      range: [-2.5, 2.5]
      bins: 50
  x_scale: linear
  label: "$\\eta^{\\gamma}$"
  unit: 
  tag: eta_gamma
- formula: "photon_phi"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\phi^{\\gamma}$"
  unit: 
  tag: phi_gamma
- formula: "num_pv_good"
  binning:
    default:
      range: [0., 75.]
      bins: 20
  x_scale: linear
  label: "Number of good vertices"
  unit:
  tag: numpvgood
# - formula: "HT + lowptjets_HT"
#   binning:
#     default:
#       range: [10., 1400.]
#       bins: 20
#   x_scale: log
#   label: "$H_\\mathrm{T}$ (including low-pt jets)"
#   unit: GeV
#   tag: HT
- formula: "dphi_visibles_ptmiss"
  binning:
    default:
      range: [-4., 4.]
      bins: 40
  x_scale: linear
  label: "$\\Delta\\phi(\\gamma + \\mathrm{jets}, p_\\mathrm{T}^{miss})$"
  unit: 
  tag: dphi_visibles_ptmiss
