files:
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_20.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_19.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_10.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_25.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_24.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_14.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_13.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_16.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_11.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_21.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_18.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_12.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_17.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_15.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_23.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/large_root/ZZTo2L2Nu_p0_Dilepton-MC_22.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_1.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_2.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_3.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_4.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_5.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_6.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_7.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_8.root
- /eos/cms/store/group/phys_smp/ZZTo2L2Nu/HZZsample/2018/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/ZZTo2L2Nu_p0_Dilepton-MC_9.root
mean_weight: 0.9737441463416141
num_events: 56886000
num_selected_events: 5289717
stem: ZZTo2L2Nu
weights:
  lhe_scale: true
  ps_scale: true
