input_dir: "../../batch_singlephoton_2016noHIPM/merged"
output_dir: "../../batch_singlephoton_2016noHIPM/merged"
samples:
  - name: 'Data'
    multiplier: '1.0'
  - name: 'ZNuNuGJets_Semi-data-driven'
    multiplier: '-1.0'
  - name: 'WGToLNuG'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_Data'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_GJets'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_QCD'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_DYJetsToLL_PtZ'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_TTJets'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_s-channel'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_t-channel'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_tW'
    multiplier: '-1.0'
  - name: 'TTGJets'
    multiplier: '-1.0'
  - name: 'TGJets'
    multiplier: '-1.0'
  - name: 'QCD'
    multiplier: '-1.0'

nvtx_weight_filepath: "../../data/InstrMetReweighting/weight_nvtx_2016noHIPM.root"
eta_weight_filepath: "../../data/InstrMetReweighting/weight_eta_2016noHIPM.root"
pt_weight_filepath: "../../data/InstrMetReweighting/weight_pt_2016noHIPM.root"
