input_dir: "../../batch_singlephoton_2018/merged"
output_dir: "../../batch_singlephoton_2018/merged"
samples:
  - name: 'Data'
    multiplier: '1.0'
  - name: 'ZNuNuGJets_Semi-data-driven'
    multiplier: '-1.0'
  - name: 'WGToLNuG'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_Data'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_GJets'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_QCD'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_DYJetsToLL_PtZ'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_TTTo2L2Nu'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_TTToSemiLeptonic'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_s-channel'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_t-channel'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ST_tW'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WWTo1L1Nu2Q'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WWTo2L2Nu'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WZTo1L1Nu2Q'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WZTo1L3Nu'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WZTo2Q2L'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_WZTo3LNu'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ZZTo2L2Nu'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ZZTo2Q2L'
    multiplier: '-1.0'
  - name: 'WJets_Data-driven_ZZTo4L'
    multiplier: '-1.0'
  - name: 'TTGJets'
    multiplier: '-1.0'
  - name: 'TGJets'
    multiplier: '-1.0'
  - name: 'QCD'
    multiplier: '-1.0'

nvtx_weight_filepath: "../../data/InstrMetReweighting/weight_nvtx_2018.root"
eta_weight_filepath: "../../data/InstrMetReweighting/weight_eta_2018.root"
pt_weight_filepath: "../../data/InstrMetReweighting/weight_pt_2018.root"
